[keys]
back = ]
quit = q
down = j
up = k
delete = D
read = \r
archive = A
spam = S
write = w
prev_folder = h
next_folder = l
goto_top = gg
goto_bottom = G

[general]
response_time = 20

[debug]
logging = off
