# Vim like key mappings
# <bs>           Backspace
# <tab>          Tab
# <cr>           Enter
# <esc>          Escape
# <space>        Space
# <up>           Up arrow
# <down>         Down arrow
# <left>         Left arrow
# <right>        Right arrow
# <f1> - <f12>   Function keys 1 to 12
# <insert>       Insert
# <del>          Delete
# <home>         Home
# <end>          End
# <pageup>       Page-Up
# <pagedown>     Page-Down
# <C-key>        Ctrl + key    # Not implemented yet
# <S-key>        Shift + key   # Not implemented yet but can use uppercase characters instead
# <A-key>        Alt + key     # Not implemented yet

[keys]
quit = q

# Navigation
down = j
up = k
top = gg
bottom = G
prev_folder = h
next_folder = l
select = <space>

# Views
show_addr = <tab>

# Actions
delete = D
read = <cr>
archive = A
spam = S
write = w

# Additional keys when viewing an email
back = <esc>
page_down = }
page_up = {

[general]
# No. of milliseconds to wait between updates
response_time = 60

[debug]
logging = off
